### ISSUE TITLE
About commas

### ISSUE THREAD

**Issue by juliomatcom** [IonicaBizau/code-style#9]
Hello @IonicaBizau , why do you use:

> commas at the beginning of the line, not at the end.

Any reason  or is just particulary thing?

Thank you

**Comment by IonicaBizau** [comment]
Hey @juliomatcom!

To be really honest, it's just because I like how it looks like, and I feel more productive too.
Here are some interesting discussions:
- http://ajaxian.com/archives/is-there-something-to-the-crazy-comma-first-style
- https://gist.github.com/isaacs/357981
- http://stackoverflow.com/a/10483845/1420197

For me it's more like a particular thing, but it probably has its pros & cons. 😄
